### ISSUE TITLE
Unable to run the analysis

### ISSUE THREAD

**Issue by ozagordi** [cmmid/CovidItalyNow#1]
Hi!
Thanks for sharing this set of fantastic resources.

I can't reproduce the analysis, it gets stuck while "Downloading linelist data". I went through the code and it seems that I can't download the csv file from Google sheets. In `NCoVUtils::get_international_linelist`, downloading from `https://docs.google.com/spreadsheets/d/1itaohdPiAeniCXNlntNztZ_oRvjh0HsGuJXUJWET008/pub` doesn't seem to work.

Is that right?

Thanks again and kudos for the great work you've been doing.

**Comment by seabbs** [comment]
np - sorry you have had difficulties

So this is relying on a public line list in a google sheet that is getting too many users. To try and mitigate this we have been using `memoise` to cache the line list once downloaded but clearly that is no longer enough. I will open an issue in `NCoVUtils` and look at resolving as this is just as much an issue for us as you! 

Thanks for taking the time to look through the code.

**Comment by ozagordi** [comment]
Thank you again. If I can be of any further help...
