### ISSUE TITLE
Failure to reproduce in docker

### ISSUE THREAD

**Issue by ekg** [cmmid/CovidItalyNow#3]
I'm trying to update the analysis to reflect the last week. However, I can't reproduce the process.

I'm using docker.

```
docker build . -t coviditalynow
docker run --dns 8.8.8.8 -d -p 8787:8787 --name covidglobalnow -e USER=coviditalynow -e PASSWORD=coviditalynow coviditalynow
docker exec -ti covidglobalnow bash
```

Then, in the image:

```
Rscript utils/update_nowcasts.R
```

This fails as shown:

```
....
....
Running pipeline for 2020-03-26
Running the pipeline for: Abruzzo, Basilicata, Calabria, Campania, Emilia Romagna, Friuli Venezia Giulia, Lazio, Liguria, Lombardia, Marche, Molise, Piemonte, Puglia, Sardegna, Sicilia, Toscana, Trentino-Alto Adige, Umbria, Valle d'Aosta, Veneto
Running pipelines by region
 Progress: ──────────────────────────────────────────────────────────────── 100%

Running Rt pipeline for Abruzzo
Using default sample of serial intervals with mean (sd) of 4.7 (2.9)
Using default Rt prior of 2.6 (2)
Fitting reporting delay between the 2020-01-24 and the 2020-03-26
Exponential selected as the best fit for the delay distribution
Nowcasting using fitted delay distributions
Estimate time-varying R0
Summarising time-varying R0
Error in eval(bysub, x, parent.frame()) : object 'type' not found
Calls: <Anonymous> ... resolve.list -> signalConditionsASAP -> signalConditions
In addition: Warning messages:
1: Removed 18 rows containing missing values (position_stack). 
2: Removed 23 row(s) containing missing values (geom_path). 
3: Removed 23 row(s) containing missing values (geom_path). 
Execution halted
```

I first attempted to build and run outside of docker (on ubuntu 20.04) but I ran into the same error.

Would you please take a look at this?

I am doing what I can to explain the situation here in Italy to others, and these estimates of R0 are really helpful in doing so. But, they need to reflect the last week to be credible.

**Comment by seabbs** [comment]
Hi @ekg, 

Thanks for reaching out. We are in the middle of making extensive backend changes hence the issues you are having. I would recommend rolling back to the commit for `EpiNow` from the date the results were last updated to be sure you have a compatible version. Hopefully, we will have our updated estimates (and improved) online shortly.

**Comment by ekg** [comment]
Thanks @seabbs! Which commit did you use to make the last summary report? The log in epinow doesn't make it very clear.

I'm doing this to rollback epinow:

```
remotes::install_github("epiforecasts/EpiNow", dependencies = TRUE, ref = "1ef2ab76040724738beb8286e1dc4554fc0f6b85")
```

**Comment by jhellewell14** [comment]
Hi Erik, 

I just had a quick look back through the commit history, I think that should be the the one that you want. Let me know if it doesn't work and I'll do some more digging. 

Cheers,
Joel

**Comment by ekg** [comment]
Thanks! I'm running the update now and it looks to have passed the point where I hit the error before.

I need this to support some ongoing conversations about the effects of the quarantine in Italy.

I look forward to your improvements. Please ping me here or by email when you have them!

**Comment by ekg** [comment]
Closing this as the bug is due to ongoing development and dependency specification which we worked out.

**Comment by seabbs** [comment]
Glad you got it working. Hopefully, we will be back online with updates soon!
